version: '3.8'

services:
  postgres:
    image: postgres:12.20-alpine
    container_name: local_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: local_rabbitmq
    ports:
      - "5672:5672"       # RabbitMQ protocol
      - "15672:15672"     # Web management console
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  redis:
    image: redis:7-alpine
    container_name: local_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"  # Expose RTSP port to host
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml

volumes:
  postgres_data:
  redis_data:
